# -*- coding: utf-8 -*-
"""人工知能論基礎_Final_例

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp1l7QJlYk1m1Bidh4k3EttXWMnmTt36
"""

!pip install japanize_matplotlib

import japanize_matplotlib

import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
import matplotlib.pyplot as plt

# データ取得（Apple株、5年分）
ticker = 'AAPL'
data = yf.download(ticker, period='5y')['Close'].values.reshape(-1,1)

# 正規化とウィンドウ作成（過去60日→次日）
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data)

def create_dataset(data, time_step=60):
    X, y = [], []
    for i in range(len(data)-time_step-1):
        X.append(data[i:(i+time_step), 0])
        y.append(data[i+time_step, 0])
    return np.array(X), np.array(y)

time_step = 60
X, y = create_dataset(data_scaled, time_step)
X = X.reshape(X.shape[0], X.shape[1], 1)

# 訓練/テスト分割（80%）
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# LSTMモデル（多層+Dropoutで過学習防止）
model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(time_step, 1)),
    Dropout(0.2),
    LSTM(50, return_sequences=False),
    Dropout(0.2),
    Dense(25),
    Dense(1)
])
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_test, y_test), verbose=1)

# 予測と逆正規化
y_pred = model.predict(X_test)
y_pred = scaler.inverse_transform(y_pred.reshape(-1,1))
y_test_inv = scaler.inverse_transform(y_test.reshape(-1,1))

# 可視化（実測vs予測）
plt.figure(figsize=(12,6))
plt.plot(y_test_inv, label='実測')
plt.plot(y_pred, label='予測')
plt.title(f'{ticker} Next day closing price forecast')
plt.legend()
plt.show()

# 方向的中率計算
direction_acc = np.mean(np.sign(y_test_inv[1:] - y_test_inv[:-1]) == np.sign(y_pred[1:] - y_pred[:-1]))
print(f"方向的中率: {direction_acc:.2%}")

# 次週予測例（最新60日入力）
latest = data_scaled[-time_step:].reshape(1, time_step, 1)
next_pred = model.predict(latest)
next_price = scaler.inverse_transform(next_pred)[0][0]
print(f"次日予測終値: ${next_price:.2f}")

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import numpy as np

# 予測と実測（逆正規化済み）: y_pred, y_test_inv を使用
mse = mean_squared_error(y_test_inv, y_pred) #実測値と予測値の「平均的なズレ」を、元の価格スケール（ドル）で表した指標。

rmse = np.sqrt(mse)
print(f"RMSE: {rmse:.4f}")

mae = mean_absolute_error(y_test_inv, y_pred) #実測値と予測値の絶対誤差の平均で、「平均して何ドルくらいズレているか」をそのまま示す指標
print(f"MAE: {mae:.4f}")

